# Generated by Django 5.2 on 2025-04-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.JSONField(),
        ),
    ]
